from django.db import models


class Tag(models.Model):
    """
    A Media category generated by the user selection
    """


    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Media(models.Model):
    """
    One media file (audio, Image, video)
    """

    MEDIA_TYPES = (
        ('IMG', 'Image'),
        ('AUD', 'Audio'),
        ('VID', 'Video'),
        ('LNK', 'Link'),
    )

    name = models.CharField(max_length=250)
    type = models.CharField(max_length=3, choices=MEDIA_TYPES)
    file = models.FileField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='media_set')


    def __str__(self):
        return self.name

